# docker-compose build, docker-compose run, docker-compose up

# создание самого джанго приложения в папке WORKDIR /service
# docker-compose run --rm web-app sh -c "django-admin startproject service ."
# --rm — после выполнения команды контейнер будет удалён (чтобы не оставался "мусор")
# docker-compose run --rm web-app sh -c "python manage.py migrate"
# docker-compose run --rm web-app sh -c "python manage.py shell_plus --ipython"

services:
  # web-app: — это имя сервиса. Оно произвольное и обозначает один контейнер
  # (или группу одинаковых контейнеров), который будет запущен в составе проекта
  web-app:
    build:
      # context — это путь к директории, который будет использоваться Docker для поиска всех необходимых файлов, таких
      # как Dockerfile, исходный код приложения, зависимости и любые другие файлы, которые могут понадобиться в процессе сборки контейнера
      # Если в контексте сборки будет много ненужных файлов (например, .git или другие большие папки), можно
      # использовать файл .dockerignore, чтобы исключить ненужные файлы из контекста сборки.
      context: .
    ports:
      # Первое число — это порт на хост-машине ( на компьютере или сервере), через который взаимодействовать
      # с контейнером. Второе число (8000) — это порт внутри контейнера, на котором приложение будет слушать запросы.
      - "8000:8000"
    volumes:
      # монтирование тома между хостом и контейнером позволяет синхронизировать файлы между хостом и контейнером во время его работы
      # подключаем локальную папку к контейнеру, Это означает, что любые изменения в локальной папке моментально отражаются в контейнере
      - ./service:/service

    environment:
      - DB_HOST=database   # ссылка на другой сервис docker-compose с бд
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    # sh -c: Это команда для запуска шелл-скрипта. sh — это командный интерпретатор (shell), а -c — параметр, который
    # позволяет передать строку команд для выполнения. То есть, здесь мы передаем команду для выполнения, как строку.
    # 0.0.0.0 — это привязка сервера ко всем доступным сетевым интерфейсам, что позволяет подключаться к
    # серверу не только изнутри контейнера, но и извне.
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    # указываем что этот сервис не должен быть запущен раньше чем сервис с дб
    depends_on:
      - database

  database:
    # берём официальный image postgresql из docker-hub на минифицированном линуксе
    image: postgres:14.6-alpine
    environment:
      # Эти переменные окружения используются для автоматической настройки базы данных при старте контейнера PostgreSQL.
      # Они задают начальную конфигурацию базы данных и позволяют другим сервисам подключаться к базе, используя эти учетные данные.
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass