FROM node:20 AS build
WORKDIR /app
COPY ./react-app/package*.json ./
RUN npm install
COPY ./react-app .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /react
COPY ./service/static /static
COPY ./conf/prodnginx.conf /etc/nginx/conf.d/default.conf
