
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for services to be healthy
        run: |
          docker-compose ps
          timeout 300 bash -c 'until docker-compose ps | grep "healthy"; do sleep 10; done'

      - name: Run tests (если есть)
        run: |
          docker-compose exec web-app python manage.py test

      - name: Stop containers
        if: always()
        run: |
          docker-compose down